### ISSUE TITLE
How to cite in papers?

### ISSUE THREAD

**Issue by GillianGrayson** [jrzaurin/pytorch-widedeep#105]
Hi!

Awesome package!
How to correctly cite it in papers? Do you have connected publication on arxiv.org or any doi?

Thanks!

**Comment by 5uperpalo** [comment]
Hi @GillianGrayson , thank you for your question.

We want to avoid a non-peer-reviewed process, but we also believe in open-source code. For these reasons, we decided to make the library cite-able using [Journal of Open Source Software(JOSS)](https://joss.theoj.org/). We need to "clean up" the related [short paper](https://github.com/jrzaurin/pytorch-widedeep/tree/joss_paper/mkdocs/paper_JOSS) a bit, and we will start the review process in the upcoming days. If you are already in the process of finishing a conference/journal paper, then please, for now, use just the following bib reference:
```
@manual{pytorch_widedeep,
  title={pytorch-widedeep},
  note="[Online]. Available at: https://github.com/jrzaurin/pytorch-widedeep"
```
