### ISSUE TITLE
Which version of Pytorch should be used?

### ISSUE THREAD

**Issue by Yiming-Deng** [jrzaurin/pytorch-widedeep#106]
I have tried to use torch1.11.0+torchvision0.12.0 and torch1.7.1+torchvision0.8.2, but report errors like "No module named 'torchvision.models._api'" and "cannot import name 'RandomInvert' from 'torchvision.transforms'". I guess it maybe the version of pytorch that I used is higher than the project used. So which version of Pytorch should be used in this project?

**Comment by jrzaurin** [comment]
hey @Yiming-Deng 

look: 

```python
>>> import torch
>>> import torchvision
>>> torch.__version__
'1.12.1'
>>> torchvision.__version__
'0.13.1'
>>> from torchvision.transforms import RandomInvert
>>> import pytorch_widedeep as wd
>>> wd.__version__
'1.2.0'
```
Please, hope it helps, let me know if you have other issues :) and thanks for opening the issue!

**Comment by Yiming-Deng** [comment]
@jrzaurin , Thanks for your help, I use "pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113" and "pip install pytorch-widedeep==1.2.0". And it works fine now.
