### ISSUE TITLE
No module named 'pytorch_widedeep.datasets'

### ISSUE THREAD

**Issue by zhouyongxiu** [jrzaurin/pytorch-widedeep#108]
I pip install pytorch_widedeep, but run example code get No module named 'pytorch_widedeep.datasets'

**Comment by jrzaurin** [comment]
hey @zhouyongxiu 

which version of the library are you using? 

Look:

```bash
pyenv virtualenv 3.8.12 test_datasets
pyenv activate test_datasets
pip install pytorch-widedeep
```

then 

```python
python
Python 3.8.12 (default, Mar 14 2022, 12:06:37)
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytorch_widedeep
>>> from pytorch_widedeep.datasets import load_adult
>>> pytorch_widedeep.__version__
'1.2.0'
>>>
```

**Comment by zhouyongxiu** [comment]
> ```python
> pytorch_widedeep.__version__
> ```

my version is '1.0.5', and pip in my macos

**Comment by jrzaurin** [comment]
Could you update?

**Comment by zhouyongxiu** [comment]
when I run pip install pytorch-widedeep==1.2.0, I get 
ERROR: Could not find a version that satisfies the requirement pytorch-widedeep==1.2.0 (from versions: 0.3.7, 0.4.1, 0.4.2, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 1.0.0, 1.0.5)
ERROR: No matching distribution found for pytorch-widedeep==1.2.0

**Comment by jrzaurin** [comment]
I mean, at this point I really don't know what to tell you

![Uploading Screenshot 2022-09-30 at 12.27.55 PM.png…]()

**Comment by zhouyongxiu** [comment]
I update my python to 3.7 and solved this problem, thanks !
