### ISSUE TITLE
no module named 'torchvision.models._api'

### ISSUE THREAD

**Issue by wangzyon** [jrzaurin/pytorch-widedeep#114]
run quick start demo，raise from ./pytorch_widedeep/wdtypes.py line 69

torchvision version 0.9.0+cu111

**Comment by jrzaurin** [comment]
hey @wangzyon 

See if this helps: https://github.com/jrzaurin/pytorch-widedeep/issues/106

**Comment by wangzyon** [comment]
> hey @wangzyon
> 
> See if this helps: #106

thanks
