### ISSUE TITLE
problem with saint prediction 

### ISSUE THREAD

**Issue by tuhm** [jrzaurin/pytorch-widedeep#116]
Hi there!

I got into this somewhat weird behavior with `predict_proba `of trainer when I choose to use SAINT for deeptabular model. 
The results are different when I call `predict_proba` on a full dataset (many observation) and retrieve n-th element of the predictions versus when I call `predict_proba `on n-th element of the dataset (single observation). The features are essentially the same, but the predictions are different and it looks as if inference is made off of some information of a batch (I attached a code below for illustration purposes). Also, this happens when SAINT is used for deeptabular but does not seem to happen when TabMlp is used (I haven't tested other models yet, but still). 

Can you kindly check this out and give your thoughts on this? Thank you for your awesome work, nonetheless ! 

```
import numpy as np
import pandas as pd
import torch

from pytorch_widedeep.preprocessing import WidePreprocessor, TabPreprocessor
from pytorch_widedeep.training import Trainer
from pytorch_widedeep.models import Wide, TabMlp, WideDeep, SAINT
from pytorch_widedeep.metrics import Accuracy, Precision
from pytorch_widedeep.datasets import load_womens_ecommerce

df = load_womens_ecommerce(as_frame=True)

# to be safe, but one can me more gentle here
df = df.dropna().reset_index(drop=True)

# just aesthetics
df.columns = [c.lower().replace(" ", "_") for c in df.columns]

# classification
df["target"] = (df.rating >= 4).astype("int")
target = df["target"].values

cat_embed_cols = [
    ("department_name", 3),
    ("class_name", 5)
    
]
continuous_cols = ["age", "recommended_ind",	"positive_feedback_count"]

tab_preprocessor = TabPreprocessor(
    embed_cols=cat_embed_cols, continuous_cols=continuous_cols
)
X_tab = tab_preprocessor.fit_transform(df)

tab_mlp = SAINT(
    column_idx=tab_preprocessor.column_idx,
    cat_embed_input=tab_preprocessor.cat_embed_input,
    continuous_cols=continuous_cols
)

tab_model = WideDeep(deeptabular=tab_mlp)

tab_trainer = Trainer(
    model=tab_model,
    objective="binary",
    optimizers=torch.optim.SGD(tab_model.parameters(), lr=0.001),
    metrics=[Accuracy],
)

tab_trainer.fit(X_tab=X_tab, target=target, n_epochs=2, batch_size=32, val_split=0.2)

y_pred = tab_trainer.predict_proba(X_tab = X_tab)

print(y_pred[50])
print(tab_trainer.predict_proba(X_tab = X_tab[50,:].reshape(1, -1)))
```

**Comment by jrzaurin** [comment]
Hi @tuhm, thanks for using the library! 

This is due to the row attention mechanism, that makes the prediction on a row dependent on the companion rows in the batch. In other words, the representation of a data point depends on other points. The variation should not be substantial, but some variation in the representation of a data point (and in consequence in its corresponding prediction) is possible depending on the companion rows.

If you replace `SAINT` with the `TabTransformer` or the `FTTransformer` (or any other attention based model that is not SAINT) this "effect" will dissapear.

If you want to have a look to our SAINT implementation and the row attention mechanism have a look here: 
https://github.com/jrzaurin/pytorch-widedeep/blob/f3297c4abaf7097e33ac0fdd13982c7e6bef7275/pytorch_widedeep/models/tabular/transformers/_encoders.py#L81

and if you need further details let me know and we can post an explicit example.

**Comment by tuhm** [comment]
I see! Basically, the companion rows give context in which a row occurs and that the representation of a data point can be (almost, should be) different depending on what group it was in?!  and when you said the effect will disappear with `TabTransformer` or the `FTTransformer` is because it only use attention on column-level? 
 
I guess the intended use of the algorithm is to make batch inference rather than inference on a single observation, although it is possible. Do you think making a single inference (no other companion) can still benefit from the inter-sample attention?

**Comment by jrzaurin** [comment]
Hi @tuhm 

> The representation of a data point can be (almost, should be) different depending on what group it was in?!

Correct🙂. Sounds/Is a bit wild, but yeah, that is my understanding of the algorithm. As I mention, the changes in prediction values should be small.

> is because it only use attention on column-level?

yeah, the attention mechanism here is more standard. I have attached a small adaptation of your code to illustrate what I mean: 

```python
import torch

from pytorch_widedeep.datasets import load_womens_ecommerce
from pytorch_widedeep.metrics import Accuracy
from pytorch_widedeep.models import (
    SAINT,
    FTTransformer,
    TabFastFormer,
    TabTransformer,
    WideDeep,
)
from pytorch_widedeep.preprocessing import TabPreprocessor
from pytorch_widedeep.training import Trainer

df = load_womens_ecommerce(as_frame=True)

# to be safe, but one can me more gentle here
df = df.dropna().reset_index(drop=True)

# just aesthetics
df.columns = [c.lower().replace(" ", "_") for c in df.columns]

# classification
df["target"] = (df.rating >= 4).astype("int")
target = df["target"].values

cat_embed_cols = [("department_name", 3), ("class_name", 5)]
continuous_cols = ["age", "recommended_ind", "positive_feedback_count"]

tab_preprocessor = TabPreprocessor(
    embed_cols=cat_embed_cols, continuous_cols=continuous_cols
)
X_tab = tab_preprocessor.fit_transform(df)

tab_transformer = TabTransformer(
    column_idx=tab_preprocessor.column_idx,
    cat_embed_input=tab_preprocessor.cat_embed_input,
    continuous_cols=continuous_cols,
)

ft_transformer = FTTransformer(
    column_idx=tab_preprocessor.column_idx,
    cat_embed_input=tab_preprocessor.cat_embed_input,
    continuous_cols=continuous_cols,
)

tab_fastformer = TabFastFormer(
    column_idx=tab_preprocessor.column_idx,
    cat_embed_input=tab_preprocessor.cat_embed_input,
    continuous_cols=continuous_cols,
)

saint = SAINT(
    column_idx=tab_preprocessor.column_idx,
    cat_embed_input=tab_preprocessor.cat_embed_input,
    continuous_cols=continuous_cols,
)

idx = 10
individual_prediction_in_batch, individual_prediction = {}, {}  # type: ignore[var-annotated]
for model_name, tab_model in [
    ("TabTransformer", tab_transformer),
    ("FTTransformer", ft_transformer),
    ("TabFastFormer", tab_fastformer),
    ("SAINT", saint),
]:

    tab_model = WideDeep(deeptabular=tab_model)

    tab_trainer = Trainer(
        model=tab_model,
        objective="binary",
        optimizers=torch.optim.SGD(tab_model.parameters(), lr=0.001),
        metrics=[Accuracy],
        verbose=False,
    )

    tab_trainer.fit(
        X_tab=X_tab,
        target=target,
        n_epochs=2,
        batch_size=512,
        val_split=0.2,
    )

    y_pred = tab_trainer.predict_proba(X_tab=X_tab)

    individual_prediction_in_batch[model_name] = y_pred[idx]
    individual_prediction[model_name] = tab_trainer.predict_proba(
        X_tab=X_tab[idx, :].reshape(1, -1)
    )[0]

for model_name in individual_prediction_in_batch.keys():
    print(f"Model Name: {model_name} \n")
    print(
        f"Individual prediction in batch: {individual_prediction_in_batch[model_name]}"
    )
    print(f"Individual prediction: {individual_prediction[model_name]} \n")
```
Just run it and obtained: 

```bash
╰─ python ~/Desktop/tuhm_code.py
Model Name: TabTransformer

Individual prediction in batch: [0.50667584 0.49332413]
Individual prediction: [0.50667584 0.49332413]

Model Name: FTTransformer

Individual prediction in batch: [0.28564155 0.71435845]
Individual prediction: [0.28564155 0.71435845]

Model Name: TabFastFormer

Individual prediction in batch: [0.29969007 0.70030993]
Individual prediction: [0.29969007 0.70030993]

Model Name: SAINT

Individual prediction in batch: [0.16540647 0.83459353]
Individual prediction: [0.17934144 0.82065856]

```

> Do you think making a single inference (no other companion) can still benefit from the inter-sample attention?

In principle, row attention has been learned during training and the embeddings of each value per feature have such information encoded. Therefore, a priori, I don't see a reason why SAINT should not be used to predict on a single observation. However, personally, I have never used it that way and I normally always use batches of some size. 

I hope this helps

**Comment by tuhm** [comment]
Thank you, it was very helpful ! Again, genuinely appreciate your great work :)

**Comment by jrzaurin** [comment]
thanks 🙂🙏
