### ISSUE TITLE
What is \sigma & b

### ISSUE THREAD

**Issue by makoeppel** [jrzaurin/pytorch-widedeep#118]
Reading throw your docs I came a cross some formulas the main one which formulates the predictions of the model contains \sigma and b. But nowhere is explained what they are. I would guess that's the bias and a sigmoid activation of the model. But a clear statement when the formula is introduced would be nice. 

Als can one not change the last activation or have a model without biases in the last layer?

**Comment by 5uperpalo** [comment]
Hi @makoeppel , it too me a bit more time as @jrzaurin also added an example with hugging face integration to the library etc... Can I close this issue ? it is fixed in joss_paper branch: https://github.com/jrzaurin/pytorch-widedeep/blob/joss_paper/mkdocs/paper_JOSS/paper.md
