### ISSUE TITLE
Feature importance

### ISSUE THREAD

**Issue by Yiming-Deng** [jrzaurin/pytorch-widedeep#119]
TabMlp, TabResnet, TabTransformer network how to derive the importance of features?

**Comment by jrzaurin** [comment]
hey @Yiming-Deng 

for the time being we do not have a direct method/function to compute feature importance. Is in my top priority thing to do in the next few months

However, you could still compute the feature importance by using the attention weights, which they are alway an attribute in attention based models. For example, using the attention weights and a similar technique to that described in the FT-Transformer paper: https://arxiv.org/abs/2106.11959v2 

Now, for non-attention based models, I have not figure out "an internal" way to do it, and maybe the best solution is to use Captum (?),  or look here: https://medium.com/@rajistics/learn-to-use-the-widedeep-pytorch-framework-5b4b9463f30

I hope this helps

**Comment by Yiming-Deng** [comment]
Thank you very much!
