### ISSUE TITLE
Pytorch-widedeep not using GPU/Cude though available

### ISSUE THREAD

**Issue by sraghavm** [jrzaurin/pytorch-widedeep#126]

**Comment by jrzaurin** [comment]
hey @sraghavm 

I mean...there is no description, but in any case, make sure you have the right version of cuda for the pytorch version. 

If this is not the case, uninstall pytorch (and torchvision) and install them with the right command/cuda version

**Comment by sraghavm** [comment]
Pytorch and CUDA are both 11.7 version.

But 'TabMlp' is taking too much time even with a small dataset. NVidia Graphic Card is showing no usage during running of the code.

**Comment by sraghavm** [comment]
Please guide me as to how I can check ? I am a novice.@jrzaurin

**Comment by jrzaurin** [comment]
Hey, ok...

The latest pytorch version is 1.x is 1.3 unless you have 2.0. 
 
Please, could you provide os version, install platform etc...

**Comment by sraghavm** [comment]
Windows 11, 
Ananconda 2022, 
Python 3.9, P
Pytorch 1.13.1, 
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

**Comment by jrzaurin** [comment]
what I would recommend is:
1. Start from a fresh environment
2. Install torch via the official command in the pytorch site according to your settings
3. Check cuda is being used
4. Then install our library via pip

**Comment by laugh-xixi** [comment]
I encountered a similar situation where CUDA shows as available, but running a tabMLP is still very slow. However, when the number of my features is only around 20, the running speed is slightly faster, even though I reinstalled PyTorch and CUDA.

**Comment by laugh-xixi** [comment]
Besides no errors being reported, according to the documentation, the GPU should be called directly when detected. I believe there is a bug here.
