### ISSUE TITLE
Licences of copied code

### ISSUE THREAD

**Issue by siboehm** [jrzaurin/pytorch-widedeep#127]
As stated in the [JOSS Paper](https://github.com/openjournals/joss-reviews/issues/5027), parts of the pytorch-widedeep packages are copied from other repositories. One example: [fastai_transforms](https://github.com/jrzaurin/pytorch-widedeep/blob/master/pytorch_widedeep/utils/fastai_transforms.py) contains code copied from [fastai/text/core.py](https://github.com/fastai/fastai/blob/dedec6be9334b1c3abfcdc9a70fe43898a74e39e/fastai/text/core.py). But fast.ai is licensed under Apache-2.0, while this package is licensed under MIT. Do these two go together? 

At the very least the copied code should be properly credited, including the original license (same for the other copied parts).

**Comment by jrzaurin** [comment]
I am actually not 100% sure, we'll check. The fastai code is credited in our code, and if it is not in the paper is our mistake, will fix it asap.

**Comment by siboehm** [comment]
Sounds good! Fastai is credited in the paper, that's how I found out about it :) I'm just worried about A) how apache and MIT go together and b) whether or not you need to include the original apache license text in `fastai_transforms.py` (instead of just the credit comment).

**Comment by jrzaurin** [comment]
Hey @siboehm 

I am not sure about A, you are right, that needs to be checked. Let me have a look. I am bit busy this week, but let's see if between me and @5uperpalo we find a sec. 

Thanks!

**Comment by 5uperpalo** [comment]
as I understand it both licenses can be combined but we need to change the license in the library from MIT to Apache 2.0 . many of the posts that I found refer to [this](https://web.archive.org/web/20210101030518/https://dwheeler.com/essays/floss-license-slide.html) post where the most permissive license is on the left and the common license that could be used to combine them is down the "stream of arrows".
* Also, according to more "restrictive"(brackets as in general there is tiny difference) Apache 2.0 license the MIT is similar, see [Apache documentation](https://apache.org/legal/resolved.html).
* to be on a "safe side" I think we should include both MIT and Apache 2.0 license as states in [this](https://law.stackexchange.com/a/6758) post:
```
Both the Apache License and the MIT license are permissive, so incorporating MIT licensed code into your Apache licensed project is certainly allowed. Just be sure to attribute the original author for the parts your incorporated and include a copy of the MIT License terms, as required by the license. Go ahead and read it to make sure you get all the details right; it's fairly short and easy for a layperson to comprehend.
```
* another [post](https://opensource.stackexchange.com/a/11654) agreeing with this statement; more profound [answer](https://www.quora.com/Is-the-MIT-license-compatible-with-the-Apache-License-Version-2-APLv2); [MIT vs Apache 2.0 compatibility](https://fossa.com/blog/open-source-licenses-101-mit-license/)

**Summary:**
To be on "a safest possible side" we include both licenses and we should credit authors of the code - which we did and continue doing.

**Comment by 5uperpalo** [comment]
I put Apache2.0 and MIT license separately and mentioned it in the README.MD: https://github.com/jrzaurin/pytorch-widedeep/tree/joss_paper#license . Other than information from my previous post I also followed advice from here: 
* https://softwareengineering.stackexchange.com/a/371435
* https://softwareengineering.stackexchange.com/a/371526
* LIcense Syntax https://en.wikipedia.org/wiki/Software_Package_Data_Exchange:
```
For example, (Apache-2.0 OR MIT) means that one can choose between Apache-2.0 (Apache License) or MIT (MIT license). On the other hand, (Apache-2.0 AND MIT) means that both licenses apply
```
I put the licenses in joss_paper branch and I will pull request to the main branch also
