### ISSUE TITLE
Improvment proposition : Flash attention ?

### ISSUE THREAD

**Issue by Forbu** [jrzaurin/pytorch-widedeep#132]
The new [flash attention](https://github.com/HazyResearch/flash-attention) is a drop in replacement of the pytorch MultiHeadAttention with a lower memory impact and a lower latency. Do you guys think we could add it to the repo ?

**Comment by jrzaurin** [comment]
100% 😄

Let me have a look and we can plan

**Comment by Forbu** [comment]
@jrzaurin nice

**Comment by jrzaurin** [comment]
@Forbu so, want me to give it a go or do you want to contribute? :)

**Comment by Forbu** [comment]
@jrzaurin It's ok for you ? I will try to do a PR before the end of the week then :)

**Comment by jrzaurin** [comment]
of course is ok! @Forbu! and I will adjust it myself to the library standards or architecture if needed, no worries. But of course, the more the merrier 😄

**Comment by Forbu** [comment]
@jrzaurin after a little bit of research ... it seems that we have very little to do ...
I was looking at this pytorch blog (https://pytorch.org/blog/accelerated-diffusers-pt-20/) and it seems that pytorch 2.0 can enable flashattention by default (https://pytorch.org/docs/master/generated/torch.nn.functional.scaled_dot_product_attention).
Basicly we should use add [torch.backends.cuda.enable_flash_sdp()](https://pytorch.org/docs/master/backends.html#torch.backends.cuda.enable_flash_sdp) to enable the flash attention and use the torch.nn.functional.scaled_dot_product_attention torch operation.

**Comment by jrzaurin** [comment]
Hey @Forbu perfect

I will read the paper 1st and give it a go next week. Is perfecr timing since the branch `cont_cols_quantization` integrates with pytorch 2.0

Ill keep you posted and thanks!

**Comment by Forbu** [comment]
@jrzaurin After a little check it's gonna be harder that I taught ... Currently the code need to return the attention weight and this is not possible with the current pytorch implementation (https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html?highlight=scale+dot+product#torch.nn.functional.scaled_dot_product_attention).

In the code we need to compute the attention weights (I suppose this is for interpretability information) : https://github.com/jrzaurin/pytorch-widedeep/blob/3026c1ff11bf02b55eb2b6f7e26aacde03e18323/pytorch_widedeep/models/tabular/transformers/_attention_layers.py#L103

**Comment by jrzaurin** [comment]
Let me have a look to the paper, see if we can just copy the pytorch source code and adjust it a bit to return the weights 🙂

**Comment by jrzaurin** [comment]
Hi @Forbu , first, thanks for the suggestion. 

A bit late but soon, flash attention will be available in the library 😉

**Comment by Forbu** [comment]
Nice @jrzaurin ! gj !
I suppose that you have to adapt your code to flashattention v2 now (lol) (https://arxiv.org/pdf/2307.08691.pdf)

**Comment by jrzaurin** [comment]
ha! 

We just used the implementation [here](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html) and throw and error if people calls `attention_weights`

We are also adding linear attention and a few more things. PR to come soon
