### ISSUE TITLE
[Question] Can I use a List of sequence indices as an Input? 

### ISSUE THREAD

**Issue by Ishitori** [jrzaurin/pytorch-widedeep#133]
I have a feature column which is an array containing list of items a user has interacted with. I found a Kaggle example with a similar situation where the author of the notebook uses this kind of feature: https://www.kaggle.com/code/matanivanov/wide-deep-learning-for-recsys-with-pytorch

Is it possible to do the same thing using Pytorch-widedeep library?

**Comment by Ishitori** [comment]
Yes, you can think of this as a list of tokens. It is usually something as a history of purchases, or as in Kaggle example, a list of already watched movies. The order might matter or might not. In my case it does (items are ordered by decreasing of frequency of interaction).

**Comment by jrzaurin** [comment]
@Ishitori sorry I did not have time today, I think it will have to wait until Fday. But if order matters, then a "standard" `WideDeep` architecture where the deep component is an MLP wont work, right? in that case you would prefer an RNN or a transformer? (note that at the moment we do not support Transformer-based models for the text component. My next updgrade to the library is integrate it with Huggingace.

**Comment by ncsilvaa** [comment]
Hey everyone! This is an interesting feature for recommender systems. 
Could you provide an example of how to use it? 
Is something possible to do with the current version of the library? 
Thanks

**Comment by jrzaurin** [comment]
Ill comment on this asap, travelling at the moment 🙂

**Comment by AresDan** [comment]
Any progress on this topic? Faced similar issue

**Comment by jrzaurin** [comment]
I have holidays approaching soon and I will address some of the open issues, including this :) 

thanks!

**Comment by jrzaurin** [comment]
hi @Ishitori @AresDan and @ncsilvaa 

I will soon open a PR form the `wide_deep_recsys` branch. In the meantime, you have an example of how to use the library for recsys following the notebook that @Ishitori mentioned in his first comment. All the code is here: https://github.com/jrzaurin/pytorch-widedeep/tree/wide_deep_recsys/examples/scripts/wide_deep_for_recsys

I still have to add some unit tests and I will also include a notebook with more explanations here and there. But in the meantime you can have a look to that code which I hope answers the questions here. 

Any other question, please, let me know :)

**Comment by jrzaurin** [comment]
PR #183 addresses this issue
