### ISSUE TITLE
Minor grammatical thing

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#138]
This is an editorial comment to your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5027).

On line 21, I think it makes sense to remove "the" in front of "text", as highlighted below:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/21175639/228639101-7c573d03-6c09-47e1-9358-79b3714ce69f.png">

**Comment by 5uperpalo** [comment]
fixed in [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf)
![image](https://user-images.githubusercontent.com/36483359/233194060-f28dc32c-89c9-4dd2-89ec-e87e6be0f9fe.png)
