### ISSUE TITLE
Reference to Figure 1

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#141]
This is an editorial comment to your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5027).

On line 41, please make sure the word "Figure" appears only once:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/21175639/228641172-63e065c2-0055-4d8d-852f-b985f1f297d4.png">

**Comment by 5uperpalo** [comment]
fixed in [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf)
![image](https://user-images.githubusercontent.com/36483359/233197013-22a982a2-ba81-47de-9cb3-87ececa19c0f.png)
