### ISSUE TITLE
Cross product transformation

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#144]
This is an editorial comment to your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5027).

Please remove the following part from the paper, lines 58-62:

> In case you are wondering what are _"cross product transformations"_, here is a quote taken directly from the paper: _"For binary features, a cross-product transformation (e.g., "AND(gender=female, language=en)") is 1 if and only if the constituent features ("gender=female" and "language=en") are all 1, and 0 otherwise"._

**Comment by 5uperpalo** [comment]
fixed in [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf)

![image](https://user-images.githubusercontent.com/36483359/233198881-4dff77d2-829b-477d-acab-952087ddd3be.png)
