### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#148]
This is an editorial comment to your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5027). 

On line 116, please change from "slack" to "Slack", with capital S.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/21175639/228645710-8dce56a3-6c26-484e-af5f-caa2f54dd8d5.png">

**Comment by osorensen** [comment]
Also please remove the reference to Pytorch-Widedeep Slack.

**Comment by 5uperpalo** [comment]
fixed in [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf)
![image](https://user-images.githubusercontent.com/36483359/233200533-f30bf305-1d96-4e79-b58f-e2a98b6229cc.png)
