### ISSUE TITLE
Whole table prediction, Aggregate prediction, Multi-row prediction

### ISSUE THREAD

**Issue by mireklzicar** [jrzaurin/pytorch-widedeep#152]
Let's say I want to do train a tabular transformer model, but I don't want to predict target value for each row, I want to predict some value for the whole table – e.g. train the model to predict the sum of all values, some label to classify what class the table belongs and usecases like that. I know that some models can encode whole table (such as TaPas), but is it possible to do this with models implemented in this library?

**Comment by jrzaurin** [comment]
Hey @mireklzicar . The library is not designed for that, but you could the following (apart from perhaps contribute and add TaPas to our model hub 😄):  Assuming you can pad all tables (let's say you have 10k) to have the same number of rows (for example 1000) and columns (for example 10). You could encode the whole table via some of the self-supervised methods we have. Imagine that after encoding the tables you end up with 64 columns. At that point you would have a tensor of shape (10000, 1000, 64). You could treat that tensor as a set of images and run a CNN-classifier/regressor. 

Let me know if this helps
