### ISSUE TITLE
ImbalancedDataLoader - small bug

### ISSUE THREAD

**Issue by thatalfredh** [jrzaurin/pytorch-widedeep#153]
"oversample_mul" passed to model.fit() method is not passed into custom_dataloader due it to not being an element in list under _extract_kwargs() method: https://github.com/jrzaurin/pytorch-widedeep/blob/master/pytorch_widedeep/training/trainer.py

**Comment by jrzaurin** [comment]
hey @thatalfredh 

thanks for the issue, I will publish a fix when I have a sec! or you can open a PR if you wanted :)

**Comment by thatalfredh** [comment]
hey Javier, [here](https://github.com/jrzaurin/pytorch-widedeep/pull/154/commits/541730dd406cffb54da964734331e425dabd4068) it is.

**Comment by thatalfredh** [comment]
I've opened it #154 :-) thanks!
