### ISSUE TITLE
<frozen importlib._bootstrap>:914 error when importing on Google Colab

### ISSUE THREAD

**Issue by CholeskyC** [jrzaurin/pytorch-widedeep#167]
When I run from pytorch_widedeep import Trainer on Google Colab, this is the error message that I get. 
But there is no problem running the package locally, for example on PyCharm.
Really appreciate if someone can help shed some light here. Thanks

<frozen importlib._bootstrap>:914: ImportWarning: APICoreClientInfoImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _PyDriveImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _OpenCVImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _BokehImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _AltairImportHook.find_spec() not found; falling back to find_module()

**Comment by thatalfredh** [comment]
Hi, this has something to do with Colab's environment, I encountered the same warnings when reading csv files on it. That said, the warnings doesn't affect any workings of this package as I am able to use it properly with expected results for different configurations, etc.

**Comment by jrzaurin** [comment]
Thanks @thatalfredh!


Also, if it helps: https://github.com/jrzaurin/pytorch-widedeep/issues/83
