### ISSUE TITLE
EarlyStopping does not store and restore the model

### ISSUE THREAD

**Issue by LuoXueling** [jrzaurin/pytorch-widedeep#175]
Hi. I found a confusing issue in `EarlyStopping` and I think it is an essential bug. When using `EarlyStopping` without an additional `ModelCheckpoint`, the best weight will not be restored. The bug is made up of three mistakes.

Firstly, the `state_dict()` object changes while the model is training because it is not a **deep** copy (even a shallow copy `state_dict().copy()` will not work). See [this discussion](https://discuss.pytorch.org/t/state-dict-changes-with-the-model/47547/5). So the following lines are actually not storing anything.

https://github.com/jrzaurin/pytorch-widedeep/blob/9acfceca015a7553f181fb86f99a0d8ed7b5e798/pytorch_widedeep/callbacks.py#L659-L660

Secondly, if `n_epoch` is reached without triggering early stopping, the best weight is not restored, because nothing is done in `on_epoch_end` or

https://github.com/jrzaurin/pytorch-widedeep/blob/9acfceca015a7553f181fb86f99a0d8ed7b5e798/pytorch_widedeep/callbacks.py#L671-L673

Thirdly, if no `ModelCheckpoint` is used, after training ends,

https://github.com/jrzaurin/pytorch-widedeep/blob/9acfceca015a7553f181fb86f99a0d8ed7b5e798/pytorch_widedeep/training/trainer.py#L532

The method `_restore_best_weights` mistakenly thinks that the best weight is restored by `EarlyStopping` (no matter whether early stopping is triggered because of the above two points)

https://github.com/jrzaurin/pytorch-widedeep/blob/9acfceca015a7553f181fb86f99a0d8ed7b5e798/pytorch_widedeep/training/_base_trainer.py#L133-L144

The above issue would not happen if `ModelCheckpoint` is used because the best weight is correctly stored and restored.

Here is my current solution that only changes two lines, which can be your reference.

```python
from pytorch_widedeep.callbacks import EarlyStopping as ES
from copy import deepcopy as cp

class EarlyStopping(ES):
    def on_epoch_end(
        self, epoch: int, logs: Optional[Dict] = None, metric: Optional[float] = None
    ):
        current = self.get_monitor_value(logs)
        if current is None:
            return

        if self.monitor_op(current - self.min_delta, self.best):
            self.best = current
            self.wait = 0
            if self.restore_best_weights:
                self.state_dict = cp(self.model.state_dict()) # here
        else:
            self.wait += 1
            if self.wait >= self.patience:
                self.stopped_epoch = epoch
                self.trainer.early_stop = True
                if self.restore_best_weights:
                    if self.verbose > 0:
                        print("Restoring model weights from the end of the best epoch")
                    self.model.load_state_dict(self.state_dict)

    def on_train_end(self, logs: Optional[Dict] = None):
        super(EarlyStopping, self).on_train_end(logs)
        self.model.load_state_dict(self.state_dict) # and here
```

**Comment by jrzaurin** [comment]
hi @LuoXueling 

I will look to it asap. But I am wondering, would you want to contribute and fix it? 🙂

In any case, thanks for the issue and the detail explanation ;)

**Comment by LuoXueling** [comment]
Sure. I will make a PR soon.

**Comment by LuoXueling** [comment]
Done. It works on my own (complicated) code, but I currently have no idea about the unit tests because it is related to overfitting.

My statement "The above issue would not happen if ModelCheckpoint is used" is not correct. This issue may affect any previous code that uses `EarlyStopping` as one of the callbacks, no matter whether `ModelCheckpoint` is used because of the above third point.

**Comment by jrzaurin** [comment]
I will fix both `EarlyStopping` and `ModelCheckpoint` and also the restoring routine to avoid discrepancies between the two restoring processes or at least letting the user know about them

**Comment by jrzaurin** [comment]
I will open a PR from the `fix_restore_best_weights` that will fix this issue and improve the restoring functionality
