### ISSUE TITLE
Wrong paper links on ContrastiveDenoisingTrainer

### ISSUE THREAD

**Issue by artempuzanov** [jrzaurin/pytorch-widedeep#187]
Hello!

The links in [documentation for ContrastiveDenoisingTrainer](https://pytorch-widedeep.readthedocs.io/en/latest/pytorch-widedeep/self_supervised_pretraining.html#pytorch_widedeep.self_supervised_training.ContrastiveDenoisingTrainer
) for [SAINT: Improved Neural Networks for Tabular Data via Row Attention and Contrastive Pre-Training](https://arxiv.org/abs/2203.05556) are leading to **On Embeddings for Numerical Features in Tabular Deep Learning** paper.

Correct link would be https://arxiv.org/abs/2106.01342.

It's correct the in the [guide post](https://pytorch-widedeep.readthedocs.io/en/latest/examples/16_Self_Supervised_Pretraning_pt2.html#self-supervised-pretraining-for-tabular-data)  though

P.S. great library, thank you a lot :)

**Comment by jrzaurin** [comment]
Hey @artempuzanov 

thanks! I will fix it in the next release (soon) thank you very much for letting me know

**Comment by jrzaurin** [comment]
Reference fixed in PR #194
