### ISSUE TITLE
'TextPreprocessor' object has no attribute 'embedding_matrix'

### ISSUE THREAD

**Issue by ajkdrag** [jrzaurin/pytorch-widedeep#202]
I was trying to use text processor as mentioned in the docs/examples, but I get this error. I couldn't find this attribute in the TextPreprocessor class.

**Comment by jrzaurin** [comment]
Hi @ajkdrag which example? and I will have a look :)

**Comment by ajkdrag** [comment]
You are correct. I was trying to use the baseRNN without any pretrained embeddings.
Also, a quick suggestion from you on my usecase would help.
I am trying to run a binary classification where I have a few continuous features and a text column Payee. The payee column can have strings like: "Mr. John Doe", "Nike Association" "Oakland LIP" (which are entity named , basically payee names on a bank cheque), for which the corresponding target is 1. On the other hand there are also strings like: "fifty dollars" , "pay to the order of", "p.o. box 1100/33" "Bank of panorama" etc which are not valid payee names and have a corresponding target of 0.
Inherently this is like a text classification/entity classification with additional non text features. My question is, is it okay to use Glove embeddings for this task? Should I tune the embeddings on my dataset (300 rows is all i have) ? Or should I use BaseRNN with learnable embeddings?
P.S. apologies for the long text , but any suggestion would help.

**Comment by jrzaurin** [comment]
Hi @ajkdrag 

Well...in my view I would suggest to build features out of the text columns such as 

number of tokens
number of numbers
number of letters
number of non alphanumeric characters
presence of some token/char association
etc

and build a tabular data out of these plus the other columns, which I would suggest to then plug into a GBM of your like (CatBoost, LightGBM or XGBoost) and perhaps forget about DL for this problem :) 

If you choose to use DL, I would suggest that you tokenize at character level (and/or char bigrams and trigrams) and use an RNN with learnable embeddings. 

If I were you I would start with the first option :)

**Comment by ajkdrag** [comment]
Is there a way to use gbm with wide-deep framework?
