### ISSUE TITLE
Cuda Version

### ISSUE THREAD

**Issue by ECUST-Zhang** [jrzaurin/pytorch-widedeep#206]
When I installed PyTorch-Widedeep directly, I installed CUDA12 and TORCH2.2.1 by default, but the device only supports CUDA11. After I re -reported errors after re -accordance with CUDA11 and Torch2.0.1:

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

Can I install the pytorch-widedeep of CUDA11 directly

**Comment by jrzaurin** [comment]
Hey @ECUST-Zhang 

Thanks for opening the issue

you could look in this [link](https://discuss.pytorch.org/t/cuda-versioning-and-pytorch-compatibility/189777) or [this one](https://discuss.pytorch.org/t/which-pytorch-version-2-0-1-support-cuda-11-4/190446/3). 

You could: 

1. Install torch and torchvision with cuda 11.XX support
2. Install pytorch-widedeep via pip. In pple the requirements are:
```bash
torch >= 2.0.0
torchvision >= 0.15.0
```
and there is cuda 11 support for these versions, so these libraries should not be re-installed. And these should work

Otherwise you can clone this repo, edit the requirements to the torch and torchvision version you need, and install from there:

```
# Clone the repository
git clone https://github.com/jrzaurin/pytorch-widedeep
cd pytorch-widedeep

# Edit requirements and Install 
pip install  .
```

Let me know if you have more issues :)

**Comment by ECUST-Zhang** [comment]
Hey @jrzaurin 
Thanks for your reply, but I still have some questions
By first installing cuda11, and then downloading the github project, pytorch-widedeep was successfully installed, but errors were still reported during model training or prediction.
![image](https://github.com/jrzaurin/pytorch-widedeep/assets/43837298/36871b87-67d1-40c3-a698-b78cdb498ee0)

**Comment by ECUST-Zhang** [comment]
![image](https://github.com/jrzaurin/pytorch-widedeep/assets/43837298/05d8f254-eca2-4b35-81f3-ac49fe0372f4)
![image](https://github.com/jrzaurin/pytorch-widedeep/assets/43837298/2aeb64de-4b67-472e-93c7-34259c4560f2)


> Hey @jrzaurin Thanks for your reply, but I still have some questions By first installing cuda11, and then downloading the github project, pytorch-widedeep was successfully installed, but errors were still reported during model training or prediction. ![image](https://private-user-images.githubusercontent.com/43837298/322454226-36871b87-67d1-40c3-a698-b78cdb498ee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzkzNDksIm5iZiI6MTcxMzE3OTA0OSwicGF0aCI6Ii80MzgzNzI5OC8zMjI0NTQyMjYtMzY4NzFiODctNjdkMS00MGMzLWE2OTgtYjc4Y2RiNDk4ZWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDExMDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZWQzMmYwZTg2YjY0YWZmNDEzMmRkNWE2MTQ1NzQzZWNlOWY0NGRhNzA2YWU4NmMxYWE4MTJhYTdjYTQ5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1uuzU8ljE-Qz0n3gbI1clNs5dulCVjSgbue1dB1GuCw)

**Comment by jrzaurin** [comment]
We always have lots of issues with Conda... @5uperpalo can you have a look? I don't use conda.

In the meantime, can you look [here](https://discuss.pytorch.org/t/how-to-fix-cuda-error-device-side-assert-triggered-error/137553/7) see if it helps?

maybe this is all you need
```python
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
```

It might be something related to TabNet.  I have not touched the code for that model in ages.
