### ISSUE TITLE
quick start

### ISSUE THREAD

**Issue by xylovezxy** [jrzaurin/pytorch-widedeep#210]
Hi,May I ask how to establish a quick start using multimodal data

**Comment by jrzaurin** [comment]
Hi @xylovezxy 

thanks for using the library!

In between this: https://github.com/jrzaurin/pytorch-widedeep/blob/master/examples/scripts/ecomerce_reviews_widedeep_hf.py

and this: https://pytorch-widedeep.readthedocs.io/en/latest/quick_start.html

you should be good to go :)

**Comment by xylovezxy** [comment]
Thank you very much! Best wishes for you!

**Comment by jrzaurin** [comment]
Sure, no probs! :)
