### ISSUE TITLE
movielens

### ISSUE THREAD

**Issue by xylovezxy** [jrzaurin/pytorch-widedeep#213]
Hi, do you have a demo running on the Movielens dataset? Or do we need to preprocess the movielens data ourselves？

**Comment by jrzaurin** [comment]
Look here: [wd for recsys](https://github.com/jrzaurin/pytorch-widedeep/blob/master/examples/notebooks/19_wide_and_deep_for_recsys_pt1.ipynb)

or here: [wd for recsys pt 2](https://github.com/jrzaurin/pytorch-widedeep/blob/master/examples/notebooks/19_wide_and_deep_for_recsys_pt2.ipynb)
