### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by xylovezxy** [jrzaurin/pytorch-widedeep#219]
Hi！Do you have any example code for using the Movielens dataset for CTR prediction？

**Comment by jrzaurin** [comment]
is not CTR but you have examples with the Movilens dataset here: https://github.com/jrzaurin/pytorch-widedeep/blob/master/examples%2Fnotebooks%2F19_wide_and_deep_for_recsys_pt1.ipynb 

(And part 2 of that notebook)
