### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xylovezxy** [jrzaurin/pytorch-widedeep#221]
![image](https://github.com/user-attachments/assets/f104ed13-5767-45f2-88e6-8e76cee3a9cc)
Hello, this error occurs when I run my notebook. Kernel crashes when executing code in the current or previous cell.May I ask why this is happening？

**Comment by jrzaurin** [comment]
Hey @xylovezxy 

can you please provide a more complete piece of code and the error in English? 

Cheers!

**Comment by xylovezxy** [comment]
The red error is:
Kernel crashes when executing code in the current or previous cell.
Please review the code in the cell to determine the possible cause of the malfunction.

I have successfully run both the text and deep versions, but when I tried to run the data processing module for image data, the kernel crashed.
There is a column in my dataframe, which is imd_path, which is the path of the image corresponding to the ID

**Comment by xylovezxy** [comment]
![image](https://github.com/user-attachments/assets/dd37effa-dea3-44bd-be26-f95c32ed8108)
I don't know why the program was killed

**Comment by jrzaurin** [comment]
There used to be an issue with notebooks and windows,.let me find it and I will link it there.

**Comment by xylovezxy** [comment]
Because img.col is my image path column.
I have a lot of data, but many of them correspond to the same image, so I processed many duplicate images during data preprocessing, resulting in memory overflow. I currently think this is the problem, and I am trying to modify the image preprocessing code to ensure batch processing or not to process duplicate image data.
