### ISSUE TITLE
 How to handle inputs in the pytorch-widedeep library if the dataset already contains vectorized encodings for text and image columns?

### ISSUE THREAD

**Issue by stoensin** [jrzaurin/pytorch-widedeep#223]
Thanks to all the developers for their tremendous contributions, this open-source project is fantastic. 

As mentioned in the title: when we have already used trained deep learning models to encode some text columns and image models to encode image columns, obtaining their respective embedding vectors, how do we handle such data in the development process of pytorch-widedeep? I am very much looking forward to someone being able to answer my question, thank you!!!

**Comment by jrzaurin** [comment]
Hey @stoensin 

thanks for the comments 😊. 

Treat them all as continuous cols

```python
from pytorch_widedeep import Trainer
from pytorch_widedeep.models import TabMlp, WideDeep,
from pytorch_widedeep.preprocessing import TabPreprocessor

if __name__ == "__main__":

    # your dataframe with 100s of continuos/numerical columns
    df = pd.DataFrame(...)

    continuous_cols = [c for c in df.columns]

    target = "your_target_col"
    target = df[target].values

    # Explore other params if you wanted 
    tab_preprocessor = TabPreprocessor(continuous_cols=continuous_cols)
    X_tab = tab_preprocessor.fit_transform(df)

    # we could use a "simple" MLP if all we have is a table
    tab_mlp = TabMlp(
        column_idx=tab_preprocessor.column_idx,
        continuous_cols=continuous_cols,
        ...,   # the params you might want   
    )
   
    # proceed as in the examples (as usual)
    ....
```

**Comment by stoensin** [comment]
Thank you for your reply. When I use the method you suggested, torch will give an abnormal error message: -> "TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found object", the picture below is my input data:

<img width="1688" alt="image" src="https://github.com/user-attachments/assets/9b5a3c41-2ad7-4bee-8327-19ed6fcfd99f">

the first three fields have been processed by a trained embedding model，The dimension of each vector is 512.

Is there a way in pytorch_widedeep to directly apply these vectorized features?

**Comment by jrzaurin** [comment]
Can you please paste here a small sample of the dataframe? or a dataframe that would be equivalent and you have no problem sharing?

**Comment by jrzaurin** [comment]
in the meantime here you have a fully functional example with a `df` that has all numerical columns apart from a binary target

```python
import numpy as np
import pandas as pd
import torch

from pytorch_widedeep import Trainer
from pytorch_widedeep.metrics import Accuracy
from pytorch_widedeep.models import TabMlp, WideDeep
from pytorch_widedeep.preprocessing import TabPreprocessor

use_cuda = torch.cuda.is_available()

if __name__ == "__main__":

    np.random.seed(42)

    data = np.random.randn(100, 10)

    target = np.random.randint(0, 2, 100)

    # Combine the data into a DataFrame
    df = pd.DataFrame(data, columns=[f"col_{i+1}" for i in range(10)])

    # Add the target column
    df["target"] = target

    continuous_cols = [f"col_{i+1}" for i in range(10)]
    target = "target"
    target = df[target].values

    tab_preprocessor = TabPreprocessor(continuous_cols=continuous_cols)
    X_tab = tab_preprocessor.fit_transform(df)

    tab_mlp = TabMlp(
        column_idx=tab_preprocessor.column_idx,
        continuous_cols=continuous_cols,
        mlp_hidden_dims=[32, 16],
    )

    model = WideDeep(deeptabular=tab_mlp)

    trainer = Trainer(
        model,
        objective="binary",
        metrics=[Accuracy],
    )

    trainer.fit(
        X_tab=X_tab,
        target=target,
        n_epochs=2,
        batch_size=16,
        val_split=0.2,
    )
```

**Comment by jrzaurin** [comment]
what machine are you using? 

I will look into this later, in the meantime, can you try setting `num_workers=1` when you instantiate the Trainer? 


```python
trainer = Trainer(
        model,
        objective="binary",
        metrics=[Accuracy],
        num_workers=1, 
    )
 ```

**Comment by jrzaurin** [comment]
@stoensin 

in your dataframe, the 1st 3 columns are strings when as you read them with `pd.read_csv`. Is a list of numbers, but when read by pandas you will see that is not even in the right format

```python
>>>  type(df.categories.tolist()[0])
...      str
>>> df.categories[0]
...     '[ 0.40317503  0.62021637  0.5523216  ... -0.00519936 -0.21220715\n -0.63832164]'
```

note the 3 dots and the `newline` before the last number. 

You need to turn each of these numbers in a column. Fix this and let me know if it works.
