### ISSUE TITLE
Using Wide and Deep as an Autoencoder

### ISSUE THREAD

**Issue by 42elenz** [jrzaurin/pytorch-widedeep#224]
Dear Team,
I am quiet new to the DeepLearning-Realm. I was just wondering if it would be possible to use your model as an Autoencoder and just using the encoder part after training to generate an Embedding for further analyses.

So would it be possible to get a reconstruction-loss and have an Encoder-Decoder structure?

I hope you can help me with this question and hope that it is not to trivial.

Thank you very much.

**Comment by jrzaurin** [comment]
Hey @42elenz 

yes you can, have a look here: https://github.com/jrzaurin/pytorch-widedeep/issues/216#issuecomment-2191085722
