### ISSUE TITLE
datset

### ISSUE THREAD

**Issue by xylovezxy** [jrzaurin/pytorch-widedeep#225]
Hello, the Movielens dataset in this library only has a 100k version. Can you add a 1M version. This allows for the use of larger datasets.

**Comment by jrzaurin** [comment]
Hey @xylovezxy 

Maybe you could do it yourself? 

This time is really simple, you just need the code here: https://github.com/jrzaurin/pytorch-widedeep/tree/master/pytorch_widedeep/datasets

On our side we prefer to keep the datasets relatively small to be stored in github and also to be tractable to run quick experiments
