### ISSUE TITLE
Example of chunking preprocessor use

### ISSUE THREAD

**Issue by davidfstein** [jrzaurin/pytorch-widedeep#228]
It would be helpful to have an example of how to use the chunking preprocessors. My data (tabular only) is too large to fit in memory. In this case, is it expected that we use the chunking preprocessors with the load from folder methods? Or can the chunking preprocessors be used on their own?

**Comment by jrzaurin** [comment]
Hey @davidfstein you have an example here: https://github.com/jrzaurin/pytorch-widedeep/blob/master/examples%2Fscripts%2Fairbnb_load_from_folder_regr.py

Bear in mind that I consider this functionality experimental and for now it works onlu with csv files (as parquet for example is hard to index)

You also have examples in the docs. Let me know if you have any question!

**Comment by davidfstein** [comment]
Ah perfect, thanks!
