### ISSUE TITLE
how to save and load model?

### ISSUE THREAD

**Issue by deng0515001** [jrzaurin/pytorch-widedeep#25]
exception occupied when i save model toch.save(model, a.model) and then use  toch.load(a.model) and then  preprocess_wide.transform to predict my label.

 exception like this:
This WidePreprocessor instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

please help me !

**Comment by jrzaurin** [comment]
hey @deng0515001 

Loading the model and save it is a different process than preprocessing 

The error you are obtaining is related to the fact that you have not fitted the `WidePreprocessor`

From here https://github.com/jrzaurin/pytorch-widedeep/blob/215f3bb99ad719f80df4b3ac39b07eeae1584fed/pytorch_widedeep/preprocessing/_preprocessors.py#L119

**Comment by jrzaurin** [comment]
Hi @deng0515001 

I have added a few lines at the end of the Quick start guide in the readme to help you see how to save/load model. 

Let me know if you have more problems 🙂
Cheers!
J

**Comment by javier-cazana** [comment]
Hi @deng0515001 

any luck? 

can I close this issue?

**Comment by jrzaurin** [comment]
Hi @deng0515001 

I am going to close this issue. If your problems persist I will reopen it
