### ISSUE TITLE
augmentations/transform while predicting?

### ISSUE THREAD

**Issue by aydindemircioglu** [jrzaurin/pytorch-widedeep#27]
first, thanks for the package!
i observed a strange behaviour when doing regression, maybe that's expected, but was not for me.
i tried to use transformations, so before i had:
```
train_transforms = []
model.compile (method = 'regression', .... transforms = train_transforms) 
```

and then later with new data

```
model.predict (X_wide=..., X_deep=......)
```

this worked fine.

but after changing the transformations to
```
from torchvision import transforms as tf
train_transforms = [
    tf.ToPILImage(),
    tf.RandomCrop(512, padding=64),
    tf.ToTensor()
]
model.compile (.... transforms = train_transforms) 
```

suddenly i got much too high values when predicting. i figured that might stem from the transformations, so i added 

```
transform_val = [
    tf.ToPILImage(),
    tf.ToTensor()
]
```

and added the  'transforms_val = transform_val' parameter to model.compile and changed def _predict in wide.deep.py accordingly:

```
        if X_test is not None:
            test_set = WideDeepDataset(**X_test, transforms=self.transforms_val)  # type: ignore
        else:
            load_dict = {"X_wide": X_wide, "X_deep": X_deep}
            if X_text is not None:
                load_dict.update({"X_text": X_text})
            if X_img is not None:
                load_dict.update({"X_img": X_img})
            test_set = WideDeepDataset(**load_dict, transforms=self.transforms_val)
```

this worked. was that change necessary or did i do something wrong and could have the same effect without changes?

**Comment by jrzaurin** [comment]
hey @aydindemircioglu 

thanks for the issue.

well, I am not sure what is the input format you are using (`np.array`s?) but this: 

```python
transform_val = [
    tf.ToPILImage(),
    tf.ToTensor()
]
```

is not really an augmentation. All that is doing is transform to tensor, as you know.  I will look into this further, but if there are no transforms passed to the `WideDeepDataset ` it should take care of the `ToTensor()` transformation automatically, here: https://github.com/jrzaurin/pytorch-widedeep/blob/9f610513670da8ab670047ea3f3a94f5769c31d7/pytorch_widedeep/models/_wd_dataset.py#L70

maybe is something related to this piece of code there:

```python
            # if there are no transforms, or these do not include ToTensor(),
            # then we need to  replicate what Tensor() does -> transpose axis
            # and normalize if necessary
            if not self.transforms or "ToTensor" not in self.transforms_names:
                xdi = xdi.transpose(2, 0, 1)
                if "int" in str(xdi.dtype):
                    xdi = (xdi / xdi.max()).astype("float32")
```

so to answer your question:

No, we should not need transforms in when predicting
This might be related to those pieces of code

Could you have a look inside `test_set ` with and without `transforms=self.transforms_val` and tell me what you see? 

I have the feeling it has to do with the image format and how `WideDeepDataset` handles it

let me know

Thanks!

**Comment by aydindemircioglu** [comment]
thanks for your answer, right now i'm on vacations and cant come back to the issue. but i think you pinned it down, i was probably adding the ToTensor just to avoid that scaling. and yes, i know that this is no augmentation, but it as i will at times might do "augmentations at test-time" i still think having the possibility to apply augmentations while validation make sense. it should be just a few lines of code anyway to allow that, right?

**Comment by jrzaurin** [comment]
Hey @aydindemircioglu 

no worries, I will wait until you came back from holidays for your feedback 🙂

Regarding augmentation on testing, technically you could do it, but people don't normally do it (the only case I know when you would use it is for Test Time Augmentation (TTA)). 

The reason why augmentation is not used at testing is because it is used to increase train size and for the model to generalise better. Therefore, there is not much point in doing it at test time, since by then the model must be already as generalisable as possible. But yeah, I could include it, is simply allowing the options to include transforms at `predict` time. 

Let's chat when you are back!

Enjoy your holidays
