### ISSUE TITLE
Incomplete example in deep_dense.py docstring

### ISSUE THREAD

**Issue by felixcaz** [jrzaurin/pytorch-widedeep#32]
The example in the DeepDense class doc string is missing `continuous_cols` param.
4 categorical columns and one continuous column are created, though when creating the network the `continuous_cols` is not specified so even though you pass a 5 column tensor to the model with model(X_deep) the result is not using the 5th column at all. For e.g if after running the example you do `X_deep[:, 4]=0` and then run `model(X_deep)` again you get the same result as before.

Need to add  the arg `continuous_cols=['e']` to fix.

**Comment by jrzaurin** [comment]
hey @felixcaz 

This is now sorted

Thanks for opening the issue
