### ISSUE TITLE
Directly extracting embeddings?

### ISSUE THREAD

**Issue by mlaugharn** [jrzaurin/pytorch-widedeep#37]
Hello, I would like to use the widedeep model together with pytorch-metric-learning, which uses (embedding, label) pairs. Is it possible to extract the embedding from the model in an easy fashion, e.g. perhaps with like an identity head component? 

Thank you!

**Comment by jrzaurin** [comment]
By the way, there is new version coming (the tabnet branch) in case you are interested 🙂 and thanks for using the package!
