### ISSUE TITLE
how can I get the adult dataset?

### ISSUE THREAD

**Issue by zengqixun12** [jrzaurin/pytorch-widedeep#40]
how can I get the adult dataset?

**Comment by Promisery** [comment]
[Link](https://archive.ics.uci.edu/ml/datasets/Adult) from UCI Machine Learning Repository
[Link](https://www.kaggle.com/uciml/adult-census-income) from kaggle

**Comment by jrzaurin** [comment]
Thanks @Promisery 

Ill close this
