### ISSUE TITLE
How to process data in a minibatch setting

### ISSUE THREAD

**Issue by Aceticia** [jrzaurin/pytorch-widedeep#43]
Hi! This is an amazing package, things are very clearly documented and very easy to use on any of my cases.

One question I have is how I can adapt the code here to a minibatch scenario. Looking into the trainer class definition, the fit method does initiate a custom dataloader on the dataset passed into it. So I should be able to write a custom dataloader to take care of data loading.

But where I need some pointers is how I can transform the data. The current code doesn't look like it can easily be adapted to handle partial fits, can you provide some suggestions?

##My thought on how to work around it:
I'm mainly using the TabPreprocessor. In the fit function, it first prepares embeddings for categorical features. If I create a dataframe that contains the same columns as real data and put in dummy examples that contain all possible combinations of categorical features it should work fine.

For the second step of standardizing continuous features, I'm thinking I can just write some dummy values before calling fit and overwriting the StandardScaler object with one that was already fit to all of my data.

Does this workaround seem like it would work to you? Any immediate concerns you might have? I'm currently working on this and will post any questions here. After this tight deadline, I'll also be happy to implement something more permanent to handle minibatches.

**Comment by javier-cazana** [comment]
Hey @Aceticia thank you!

ok, let's see: 

1.  If I create a dataframe that contains the same columns as real data and put in dummy examples that contain all possible combinations of categorical features it should work fine.

Not sure I follow...could you perhaps insert some pseudo code or an illustration of what you want to do? Let's see...if you real data has two columns, you would create a dataframe with the two columns, and then each column will have...what? combination of the categorical features IN THE TWO COLUMNS?

2. For the second step of standardizing continuous features, I'm thinking I can just write some dummy values before calling fit and overwriting the StandardScaler object with one that was already fit to all of my data.

to be honest, you could even contribute to the library and add the option of passing a custom "Standarizer". If not I can do it in the next release 🙂. I am still a bit confused with this: _"I can just write some dummy values before calling fit [...]"_

In any case, in case it helps, we now have custom dataloaders: https://github.com/jrzaurin/pytorch-widedeep/blob/master/pytorch_widedeep/dataloaders.py 

You could add any that you like in that module. Overall, let me see if I understand. You want to Preprocess data on the fly? i.e. like running the `TabPreprocessor` per minibatch?

Let me know and see how can I help

Also, apart from commenting here (so is visible for more users), please, join the slack channel if you wanted :) : https://join.slack.com/t/pytorch-widedeep/shared_invite/zt-soss7stf-iXpVuLeKZz8lGTnxxtHtTw

**Comment by jrzaurin** [comment]
Closing this due to lack of response/activity
