### ISSUE TITLE
corner case: seq could be empty list when preprocessing texts

### ISSUE THREAD

**Issue by sallypannn** [jrzaurin/pytorch-widedeep#46]
Hi, I think it is a corner case if seq = [] when preprocessing texts. It could lead to error in the following line.
https://github.com/jrzaurin/pytorch-widedeep/blob/8e110a93689b7b1e1838f9d68d6d9b1ff5c51adf/pytorch_widedeep/utils/text_utils.py#L118

**Comment by jrzaurin** [comment]
Hey @sallypannn 

mmmm...🤔, I can return a sequence that is just all `pad_idx` but I can't easily see an example where after tokenising and "numericalising" there is an empty sequence in the list of sequences. 

Nonetheless, I will add: 

```python
elif len(seq) ==0:
    return np.zeros(maxlen, dtype="int32") + pad_idx
```

that will solve the problem

Thanks for the issue!

**Comment by jrzaurin** [comment]
This is now fixed
