### ISSUE TITLE
How to deal with absence of values in Target Label on new Dataset?

### ISSUE THREAD

**Issue by LaxmanSinghTomar** [jrzaurin/pytorch-widedeep#52]
Hello, I was going through the sample tutorial notebooks provided by you. In the notebook: Save and Load Model and Artifacts,
when we want to evaluate our saved model on new data, you have kept "Target" in the dataframe which is in fact our Label column. The values from this column aren't available to us in the real-world and are something we are expecting our model to predict. How we are providing this as an input column (along with others) to the preprocessor, while this is something which we should be predicting instead? Is this correct?

![Screenshot 2021-09-27 at 19-13-10 jrzaurin pytorch-widedeep A flexible package to combine tabular data with text and images](https://user-images.githubusercontent.com/37807897/134920651-262723b4-16f4-4190-ace0-d4434bd5a0e1.png)

**Comment by jrzaurin** [comment]
Hey @LaxmanSinghTomar 

thanks for the question! 

If you notice, the preprocessor **does not** take the target column as an input (and assumes the user will not pass it in either the `embed_cols` and the `continuous_cols` input params. See here: https://github.com/jrzaurin/pytorch-widedeep/blob/6540cd3cb33b2d7f0ad55e73371094e0d4f9907b/pytorch_widedeep/preprocessing/tab_preprocessor.py#L130)

In the example you cite before, the `tab_preprocessor` has a `embed_cols` and `continuous_cols` attributes and only columns there will be processed and returned. If you don't pass neither continuous or categorical (embed) columns the processor will throw an error:

https://github.com/jrzaurin/pytorch-widedeep/blob/6540cd3cb33b2d7f0ad55e73371094e0d4f9907b/pytorch_widedeep/preprocessing/tab_preprocessor.py#L143

Again, **only columns included in the `embed_cols` and the `continuous_cols` will be processed** and of course those should not include the target. I can refine the docs if needed, let me know. 

Thanks agaon

**Comment by jrzaurin** [comment]
@LaxmanSinghTomar I am assuming this solved your issues so I am going to go ahead and close it. 

If you have further questions I will re-open it
