### ISSUE TITLE
FullEmbeddingDropout works during evaluation

### ISSUE THREAD

**Issue by jmpark-swk** [jrzaurin/pytorch-widedeep#61]
https://github.com/jrzaurin/pytorch-widedeep/blob/c287c870eb3e22f1a05753c821daaa715b1ed917/pytorch_widedeep/models/transformers/_embeddings_layers.py#L15
#60 
There is a bug in which FullEmbeddingDropout operates in both train and evaluation.

**Comment by jrzaurin** [comment]
@jmpark-swk just in case, this has not been fixed in the branch https://github.com/jrzaurin/pytorch-widedeep/tree/pmulinka/uncertainty

Soon to be merged to master :)
