### ISSUE TITLE
ModelCheckpoint save_best_only not working

### ISSUE THREAD

**Issue by egmaminta** [jrzaurin/pytorch-widedeep#64]
Good day! So I attempted to use the ModelCheckpoint callback in the hopes of saving the best weights throughout the training process. I was just testing so I temporarily placed 2 epochs as the number of epochs. When I checked the file folder (based on the filepath), I didn't find any '.pt' files. I checked the callbacks documentation and it seems that I didn't miss anything. May I ask if someone could enlighten me on this? I would appreciate your help!

(See screenshot below for reference)

![save_best_model](https://user-images.githubusercontent.com/90879644/144740480-cbcfbc0e-f99d-434b-8b4c-8b37a19ec5fc.PNG)

**Comment by jrzaurin** [comment]
hey @egmaminta 

if you have a look to the examples folder, for example here: 

https://github.com/jrzaurin/pytorch-widedeep/blob/e1e6a2acd7634b3e9667f14741d6fac76dea7079/examples/adult_census.py#L107

or in the docs: 

https://github.com/jrzaurin/pytorch-widedeep/blob/e1e6a2acd7634b3e9667f14741d6fac76dea7079/examples/adult_census.py#L107

you will see that optimizers, callbacks, etc, must be passed when you instantiate the `Trainer`, not to the `fit` method

In your case: 

```    
trainer = Trainer(
        model,
        objective="multiclass_focal_loss",
        optimizers=deep_optimizer, # no need of dict, you can pass it directly
        lr_schedulers=deep_sch, # no need of dict, you can pass it directly
        callbacks=[model_checkpoint],
        metrics=[Accuracy],
    )
```

Hope this helps!

Ciao!

**Comment by egmaminta** [comment]
@jrzaurin thank you, good sir! I must've missed that, oops.
