### ISSUE TITLE
how to save tab_preprocessor (standard scaler , labelencoder )?

### ISSUE THREAD

**Issue by sungreong** [jrzaurin/pytorch-widedeep#74]
With your library, when I test it, your code doesn't seem to save the file for tab_preprocessor(standard scaler, laben ecoder).
Do you know where to save it?

**Comment by jrzaurin** [comment]
Hey @sungreong 

the `TabPreprocessor` can be saved as any other python object using `picke`

Hope it helps!

**Comment by sungreong** [comment]
@jrzaurin 
thanks for your reply!
I wonder why you didn't create a function to save those objects.

**Comment by jrzaurin** [comment]
You mean like 

```python
preproc =TabPreprocessor(...)
preproc.save(dir)
```

You mean something like that. Well, we did not think it added value compared to simply pickle it, but certainly we can consider it

**Comment by sungreong** [comment]
I was just asking out of curiosity.
Thanks for your reply. When I saw 08_save_and_load_model_and_artifacts.ipynb among the examples, I was able to understand to a certain extent.
