### ISSUE TITLE
Is 'CUDA' available for pytorch-wideep?

### ISSUE THREAD

**Issue by egmaminta** [jrzaurin/pytorch-widedeep#75]
Hi! I have been getting state-of-the-art results from this library. So, kudos to the team!

I was wondering if I could use 'CUDA' or GPU as my device instead of CPU?

Thank you.

**Comment by jrzaurin** [comment]
Hi @egmaminta 

These are fantastic news! Awesome. @5uperpalo and myself put a lot of work here, so is fantastic to hear that. Thanks for letting us know

Regarding GPU, it all happens under the hood, meaning, if GPU is available, it will use it. 

Here: https://github.com/jrzaurin/pytorch-widedeep/blob/8b4c3a8acbf06b385c821d7111b1139a16b4f480/pytorch_widedeep/training/trainer.py#L48

For the time being we do not support multiple GPUs (itll happen)

Hope it helps!_

**Comment by egmaminta** [comment]
This is noted. Thank you! By the way, is there anyway I could cite the team? I'm doing a research and I'm using your package!

**Comment by jrzaurin** [comment]
I will include some citation in the Readme. Let me come back to you later here. 

And again, thanks!
