### ISSUE TITLE
How to use for seq2seq data?

### ISSUE THREAD

**Issue by Darshan2104** [jrzaurin/pytorch-widedeep#81]
Hey there,

I'm working with text generation task from given text data. new text with better semantic relation between sentences!
How to use a wide-deep network for sequential data which are not in tabular form?

I'm new to the WideDeep concept. If anybody has any idea, please help me out.

Thanks
Darshan Tank

**Comment by Darshan2104** [comment]
What is DeepText?
What does it do?
What does only the **wide+deeptext** part generate at the end?

**Comment by jrzaurin** [comment]
Hey @Darshan2104 

Already replied to your email :) 

For the time being we only support classification/regression tasks with multi-modal data 

Talk soon!
