### ISSUE TITLE
Huggingface integration

### ISSUE THREAD

**Issue by devashish-khatwani** [jrzaurin/pytorch-widedeep#82]
Is there any plan of integrating with HuggingFace to utilize in Deeptext and DeepImage?

**Comment by jrzaurin** [comment]
Hey @devashish-khatwani 

there is in fact! is one of our plans for v2 as well as the new torchvision (still unsure about including  transformers for vision). 

We are about to release v1 which will have some additional components for text and image, still not hugginface.

In summary, yes! we will integrate with hugginface I hope in the mid term. If you want to contribute you are more than welcome. In the meantime, you could always code your own text component and pass it to `WideDeep`. If you need help/advise let me know

Thanks for opening the issue!
