### ISSUE TITLE
tab2vec on text / images

### ISSUE THREAD

**Issue by w1nk** [jrzaurin/pytorch-widedeep#88]
Hello! 

  I see in the documentation (and the warning in the code), that tab2vec is only able to extract embeddings from the tabular models.  Is it still planned to change that to extract embeddings from the other 2 modalities?

**Comment by jrzaurin** [comment]
Hi @w1nk 

It is indeed. I just need a few weeks of 'less intense' work and I'll get to it. (or if you want to contribute, even better!)

I plan to find time to go back to the library in the next 1-2 weeks. 

Thanks for the question and the interest!

**Comment by w1nk** [comment]
I'll gladly contribute as I can, hopefully I can dig deep enough to give a hand.  Thanks for the work, it looks great :).
