### ISSUE TITLE
Where can I get the airbnb data?

### ISSUE THREAD

**Issue by dongfeng951** [jrzaurin/pytorch-widedeep#9]
Hi,
     Thanks for the code. Where can I get the airbnb data? Is there a link?
     Best regards!

**Comment by jrzaurin** [comment]
hey, yes, there is a link in this [notebook](https://github.com/jrzaurin/pytorch-widedeep/blob/master/examples/05_Regression_with_Images_and_Text.ipynb)

Or simply go [here](http://insideairbnb.com/get-the-data.html)

**Comment by dongfeng951** [comment]
Thanks! Best wishes!
