### ISSUE TITLE
Issue: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by rv-iiita** [jrzaurin/pytorch-widedeep#99]
Hi @jrzaurin @5uperpalo 
I was trying to implement the TabTransformer model with adult census dataset, but getting the following error which i am not sure how to resolve it, I will be greatfull if you can suggest some solution, Thank you .
here i am attaching link to colab notebook for your reference.
[**Google Colab notebook link**](https://colab.research.google.com/drive/1frREM4uHAMtpNOXY59pPS0Av2TFuHa18#scrollTo=0vUREVsAlUa2&line=2&uniqifier=1)

**Comment by jrzaurin** [comment]
Hey @rv-iiita 

I replied to you in the slack channel, but just in case, in the code, replace `cat_embed_cols` with `cat_embed_input` as you instantiate the Transformer ;)

**Comment by rv-iiita** [comment]
Thanks a lot @jrzaurin .
